test:
  secret_key_base: 10923b46a3bbb06efc4af9f1337062c3bfebfe860a084173233cfd8e86bbae6d

development:
  secret_key_base: 88df341f27b9049e2fc5ccb81234757d73ec6270e847626b779abd05283945d8

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
